### Health
GET http://localhost:8080/chat/chunks

### Health
GET http://localhost:8080/chat/documents

### Chat
POST http://localhost:8080/chat/ask
Content-Type: application/json

{
  "question": "What is the capital of France?"
}

### Chat
POST http://localhost:8080/chat/ragservice
Content-Type: application/json

{
  "text": "What is the capital of France?"
}

### Chat
POST http://localhost:8080/chat/ragservice
Content-Type: application/json

{
  "text": "What endpoint does payment service expose?"
}

### Chat
POST http://localhost:8080/chat/ragservice
Content-Type: application/json

{
  "text": "what does inventory consumes"
}